version: '3.9'
services:
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: app
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
  app:
    build: .
    environment:
      POSTGRES_DSN: postgres://app:app@postgres:5432/app?sslmode=disable
      REDIS_ADDR: redis:6379
    depends_on:
      - postgres
      - redis
    ports:
      - "8080:8080"
volumes:
  pgdata:
